services:
  bodymetrics:
    build: .
    container_name: bodymetrics
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - default
      - npm_network

networks:
  npm_network:
    external: true
    name: proxy-net
